version: '3.7'
services:

  users-srv:
    container_name: users-srv
    build: ./users-srv
    ports:
      - "8080:8080"
    expose: 
      - 8080

  blog-srv:
    container_name: blog-srv
    build: ./blog-srv
    ports:
      - "8081:8080"
    expose: 
      - 8080


  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - 27017:27017
    expose:
      - 27017

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.7-management"
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
