version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - 27017:27017
    expose:
      - 27017

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.7-management"
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
